blank_issues_enabled: false
contact_links:
  - name: Start a Discussion
    about: Use discussion to create conversation with the community, ask and answer questions, share ideas and/or announcements, and more.
    url: https://github.com/o3de/sig-ui-ux/discussions
